tardis/apps/related_info/urls.py
from django.conf.urls import url

from .views import index
from .views import list_or_create_related_info
from .views import get_or_update_or_delete_related_info


urlpatterns = [
    url(r'^(?P<experiment_id>\d+)/$', index,
        name='tardis.apps.related_info.views.index'),
    url(r'^experiment/(?P<experiment_id>\d+)/related-info/$',
        list_or_create_related_info,
        name='tardis.apps.related_info.views.list_or_create_related_info'),
    url(r'^experiment/(?P<experiment_id>\d+)/related-info/(?P<ps_id>\d+)$',
        get_or_update_or_delete_related_info,
        name='tardis.apps.related_info.views.get_or_update_or_delete_related_info'),
]

tardis/default_settings/urls.py
ROOT_URLCONF = 'tardis.urls'

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash if there is a path component (optional in other cases).
# Examples: "http://media.lawrence.com", "http://example.com/media/"
MEDIA_URL = ''

# Static content location
STATIC_URL = '/static/'

tardis/tardis_portal/models/datafile.py
import hashlib
import logging
import re
from contextlib import contextmanager
from tempfile import NamedTemporaryFile
from urllib.parse import quote

from os import path
import mimetypes


from django.conf import settings
from django.core.files import File
from django.urls import reverse
from django.db import models
from django.db import transaction
from django.db.models import Q, Sum
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.forms.models import model_to_dict
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

import magic

from .. import tasks
from .dataset import Dataset
from .storage import StorageBox, StorageBoxOption, StorageBoxAttribute

logger = logging.getLogger(__name__)

IMAGE_FILTER = (Q(mimetype__startswith='image/') &
                ~Q(mimetype='image/x-icon')) |\
    (Q(datafileparameterset__datafileparameter__name__units__startswith="image"))  # noqa


@python_2_unicode_compatible
class DataFile(models.Model):
    """A ``DataFile`` is a record of a file which includes its filename,
    its size in bytes, its relative directory, and various other meta-data.
    Each ``DataFile`` belongs to a
    :class:`~tardis.tardis_portal.models.dataset.Dataset` which usually
    represents the files from one folder on an instrument PC.

    The physical copy (or copies) of a file are described by distinct
    :class:`~tardis.tardis_portal.models.datafile.DataFileObject` records.

    :attribute dataset: The foreign key to the
       :class:`tardis.tardis_portal.models.Dataset` the file belongs to.
    :attribute filename: The name of the file, excluding the path.
    :attribute size: The size of the file.
    :attribute created_time: Should be populated with the file's creation time
      from the instrument PC.
    :attribute modification_time: Should be populated with the file's last
      modification time from the instrument PC.
    :attribute mimetype: For example 'application/pdf'
    :attribute md5sum: Digest of length 32, containing only hexadecimal digits
    :attribute sha512sum: Digest of length 128, containing only hexadecimal
        digits
    """

    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    filename = models.CharField(max_length=400)
    directory = models.CharField(blank=True, null=True, max_length=255)
    size = models.BigIntegerField(blank=True, null=True)
    created_time = models.DateTimeField(null=True, blank=True)
    modification_time = models.DateTimeField(null=True, blank=True)
    mimetype = models.CharField(db_index=True, blank=True, max_length=80)
    md5sum = models.CharField(blank=True, max_length=32)
    sha512sum = models.CharField(blank=True, max_length=128)
    deleted = models.BooleanField(default=False)
    deleted_time = models.DateTimeField(blank=True, null=True)
    version = models.IntegerField(default=1)

    @property
    def file_object(self):
        return self.get_file()

    @file_object.setter
    def file_object(self, file_object):
        """
        Replace contents of file in all its locations
        TODO: new content implies new size and checksums. Are we going to
        auto-generate these or not allow this kind of assignment ?

        :type file_object: Python File object
        """
        oldobjs = []
        if self.file_objects.count() > 0:
            oldobjs = list(self.file_objects.all())
        s_boxes = [obj.storage_box for obj in oldobjs]
        if not s_boxes:
            s_boxes = [self.get_default_storage_box()]
        for box in s_boxes:
            newfile = DataFileObject(datafile=self,
                                     storage_box=box)
            newfile.save()
            newfile.file_object = file_object
        if oldobjs:
            for obj in oldobjs:
                obj.delete()

    @property
    def status(self):
        """
        returns information about the status of the file.
        States are defined in StorageBox
        """
        return {dfo.storage_type
                for dfo in self.file_objects.filter(verified=True)}

    @property
    def is_online(self):
        """
        return False if a file is on tape.
        At this stage it checks it returns true for no file objects, because
        those files are offline through other checks
        """
        dfos = self.file_objects.filter(verified=True)
        if dfos.count() == 0:
            return True
        return any(dfo.storage_type not in StorageBox.offline_types
                   for dfo in dfos)

    def cache_file(self):
        if self.is_online:
            return True
        for dfo in self.file_objects.filter(verified=True):
            if dfo.cache_file():
                return True
        return False

    def get_default_storage_box(self):
        '''
        try to guess appropriate box from dataset or use global default
        '''
        if settings.REUSE_DATASET_STORAGE_BOX:
            dataset_boxes = self.dataset.get_all_storage_boxes_used()
            if dataset_boxes.count() == 1:
                return dataset_boxes[0]
        # TODO: select one accessible to the owner of the file
        return StorageBox.get_default_storage()

    def get_receiving_storage_box(self):
        default_box = self.get_default_storage_box()
        child_boxes = [
            box for box in default_box.child_boxes.all()
            if box.attributes.filter(
                key="type", value="receiving").count() == 1]
        if child_boxes:
            return child_boxes[0]

        loc_boxes = StorageBoxOption.objects.filter(
            key='location',
            value=getattr(settings, 'DEFAULT_RECEIVING_DIR', '/tmp'))\
            .values_list('storage_box', flat=True)
        attr_boxes = StorageBoxAttribute.objects.filter(
            key="type", value="receiving")\
            .values_list('storage_box', flat=True)
        existing_default = set(loc_boxes) & set(attr_boxes)
        if existing_default:
            return StorageBox.objects.get(id=existing_default.pop())

        new_box = StorageBox.create_local_box(
            location=getattr(settings, 'DEFAULT_RECEIVING_DIR', '/tmp'))
        new_attr = StorageBoxAttribute(storage_box=new_box,
                                       key='type', value='receiving')
        new_attr.save()
        new_box.attributes.add(new_attr)
        new_box.master_box = default_box
        new_box.save()
        return new_box

    class Meta:
        app_label = 'tardis_portal'
        ordering = ['filename']
        unique_together = ['dataset', 'directory', 'filename', 'version']

    @classmethod
    def sum_sizes(cls, datafiles):
        """
        Takes a query set of datafiles and returns their total size.
        """
        return datafiles.aggregate(size=Sum('size'))['size'] or 0

    # pylint: disable=W0222
    def save(self, *args, **kwargs):
        if self.size is not None:
            self.size = int(self.size)

        require_checksums = kwargs.pop('require_checksums', True)
        if settings.REQUIRE_DATAFILE_CHECKSUMS and \
                not self.md5sum and \
                not self.sha512sum and \
                require_checksums:
            raise Exception('Every Datafile requires a checksum')
        if settings.REQUIRE_DATAFILE_SIZES:
            if self.size < 0:
                raise Exception('Invalid Datafile size (must be >= 0): %d' %
                                self.size)
        self.update_mimetype(save=False)

        super().save(*args, **kwargs)

    def get_size(self):
        return self.size

    def getParameterSets(self):
        """Return datafile parametersets associated with this datafile.
        """
        from .parameters import Schema
        return self.datafileparameterset_set.filter(
            schema__type=Schema.DATAFILE)

    def __str__(self):
        if self.sha512sum is not None and len(self.sha512sum) > 31:
            checksum = str(self.sha512sum)[:32]
        else:
            checksum = self.md5sum or 'no checksum'
        return "%s %s # %s" % (checksum,
                               self.filename, self.mimetype)

    def get_mimetype(self):
        if self.mimetype:
            return self.mimetype
        suffix = path.splitext(self.filename)[-1]
        try:
            return mimetypes.types_map[suffix.lower()]
        except KeyError:
            return 'application/octet-stream'

    def get_view_url(self):
        render_image_size_limit = getattr(settings, 'RENDER_IMAGE_SIZE_LIMIT',
                                          0)
        if render_image_size_limit:
            if self.size > render_image_size_limit:
                return None

        viewable_mimetype_patterns = ('image/.*', 'text/.*', 'application/pdf')
        if not any(re.match(p, self.get_mimetype())
                   for p in viewable_mimetype_patterns):
            return None
        return reverse('tardis.tardis_portal.download.view_datafile',
                       kwargs={'datafile_id': self.id})

    def get_download_url(self):
        return reverse('api_download_file',
                       kwargs={'pk': self.id,
                               'api_name': 'v1',
                               'resource_name': 'dataset_file'})

    def get_file(self, verified_only=True):
        """
        Returns the file as a readable file-like object from the best avaiable
        storage box.

        If verified_only=False, the return of files without a verified checksum
        is allowed, otherwise None is returned for unverified files.

        :param bool verified_only: if False return files without verified
             checksums
        :returns: Python file object
        :rtype: Python File object
        """

        dfo = self.get_preferred_dfo(verified_only)
        if dfo is None:
            return None
        if dfo.storage_type in (StorageBox.TAPE,):

tardis/tardis_portal/models/instrument.py
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from .facility import Facility


@python_2_unicode_compatible
class Instrument(models.Model):
    '''
    Represents an instrument belonging to a facility that produces data
    '''
    name = models.CharField(max_length=100)
    created_time = models.DateTimeField(null=True, blank=True, default=timezone.now)
    modified_time = models.DateTimeField(null=True, blank=True)
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)

    class Meta:
        app_label = 'tardis_portal'
        verbose_name_plural = 'Instruments'
        unique_together = ['name', 'facility']
        ordering = ('name', )

    # pylint: disable=W0222
    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def getParameterSets(self):
        '''Return the instrument parametersets associated with this
        instrument.
        '''
        from .parameters import Schema
        return self.instrumentparameterset_set.filter(
            schema__type=Schema.INSTRUMENT)

    def _has_change_perm(self, user_obj):
        """
        Instrument objects should only be modified by members of the facility
        managers group.
        """
        return self.facility.manager_group in user_obj.groups.all()

tardis/tardis_portal/views/ajax_actions.py
# pylint: disable=http-response-with-json-dumps,http-response-with-content-type-json
"""
views that perform some action and don't return anything very useful
"""

import json
import logging

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.http import HttpResponse
from django.views.decorators.cache import never_cache

from celery import group, chord

from ..auth import decorators as authz
from ..models import Dataset
from ..tasks import cache_done_notify

logger = logging.getLogger(__name__)


@never_cache
@authz.dataset_download_required
def cache_dataset(request, dataset_id=None, notify=True):
    dataset = Dataset.objects.get(id=dataset_id)
    run_this = group(df.cache_file.s()
                     for df in dataset.datafile_set.all())
    if notify:
        run_this = chord(run_this)(
            cache_done_notify.subtask(kwargs={
                'priority': settings.DEFAULT_EMAIL_TASK_PRIORITY,
                'user_id': request.user.id,
                'site_id': Site.objects.get_current(request).id,
                'ct_id': ContentType.objects.get_for_model(Dataset).id,
                'obj_ids': [dataset_id], }))
    if hasattr(run_this, 'apply_async'):
        result = run_this.apply_async()
    else:
        result = run_this
    return HttpResponse(json.dumps({"result": str(result.id)}),
                        content_type='application/json')

tardis/tardis_portal/views/images.py
"""
views that return images or route to images
"""

from base64 import b64decode
import logging
from os import path

from django.conf import settings
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.views.decorators.cache import never_cache

from ..auth import decorators as authz
from ..models import ExperimentParameter, DatasetParameter, \
    DatafileParameter, Dataset
from ..shortcuts import return_response_error

logger = logging.getLogger(__name__)


@never_cache
def load_image(request, parameter):
    file_path = path.abspath(path.join(settings.METADATA_STORE_PATH,
                                       parameter.string_value))

    from wsgiref.util import FileWrapper
    try:
        wrapper = FileWrapper(open(file_path, 'rb'))
    except IOError:
        return HttpResponseNotFound()
    return HttpResponse(wrapper, content_type=parameter.name.units)


def load_experiment_image(request, parameter_id):
    parameter = ExperimentParameter.objects.get(pk=parameter_id)
    experiment_id = parameter.parameterset.experiment.id
    if authz.has_experiment_access(request, experiment_id):
        return load_image(request, parameter)
    return return_response_error(request)


def load_dataset_image(request, parameter_id):
    parameter = DatasetParameter.objects.get(pk=parameter_id)
    dataset = parameter.parameterset.dataset
    if authz.has_dataset_access(request, dataset.id):
        return load_image(request, parameter)
    return return_response_error(request)


def load_datafile_image(request, parameter_id):
    try:
        parameter = DatafileParameter.objects.get(pk=parameter_id)
    except DatafileParameter.DoesNotExist:
        return HttpResponseNotFound()
    datafile = parameter.parameterset.datafile
    if authz.has_datafile_access(request, datafile.id):
        return load_image(request, parameter)
    return return_response_error(request)


@authz.experiment_access_required
def display_experiment_image(
        request, experiment_id, parameterset_id, parameter_name):

    # TODO handle not exist

    if not authz.has_experiment_access(request, experiment_id):
        return return_response_error(request)

    image = ExperimentParameter.objects.get(name__name=parameter_name,
                                            parameterset=parameterset_id)

    return HttpResponse(b64decode(image.string_value), content_type='image/jpeg')


@authz.dataset_access_required
def display_dataset_image(
        request, dataset_id, parameterset_id, parameter_name):

    # TODO handle not exist

    if not authz.has_dataset_access(request, dataset_id):
        return return_response_error(request)

    image = DatasetParameter.objects.get(name__name=parameter_name,
                                         parameterset=parameterset_id)

    return HttpResponse(b64decode(image.string_value), content_type='image/jpeg')


@authz.datafile_access_required
def display_datafile_image(
        request, datafile_id, parameterset_id, parameter_name):

    # TODO handle not exist

    if not authz.has_datafile_access(request, datafile_id):
        return return_response_error(request)

    image = DatafileParameter.objects.get(name__name=parameter_name,
                                          parameterset=parameterset_id)

    return HttpResponse(b64decode(image.string_value), content_type='image/jpeg')



@authz.dataset_access_required
def dataset_thumbnail(request, dataset_id):
    dataset = Dataset.objects.get(id=dataset_id)
    tn_url = dataset.get_thumbnail_url()
    if tn_url is None:
        return HttpResponseNotFound()
    return HttpResponseRedirect(tn_url)

tardis/tardis_portal/templates/tardis_portal/add_or_edit_dataset.html
{% extends "tardis_portal/portal_template.html" %}
{% load render_bundle from webpack_loader %}
{% load widget_tweaks %}

{% block content %}
<div id="content" class="container">
  <div class="page-header">
    {% if dataset %}
    <h1>Edit dataset</h1>
    {% else %}
    <h1>Add new dataset</h1>
    {% endif %}
  </div>

  <div class="row">
    <div class="col-md-12">
      <form id="add-or-edit-dataset-form"
            class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <div class="form-group row">
          <label class="col-form-label col-md-2 " for="id_description">Description</label>
          <div class=" col-md-9 ">
            {{ form.description | add_class:"form-control" }}
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-md-2 " for="id_directory">Directory</label>
          <div class=" col-md-9 ">
            {{ form.directory | add_class:"form-control" }}
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-md-2 " for="id_instrument">Instrument</label>
          <div class=" col-md-9 ">
              {{ form.instrument | add_class:"form-control" }}
          </div>
        </div>
        <div class="form-group row">
          <div class="offset-md-2 col-md-9 text-right">
            <a class="btn btn-outline-secondary"
              {% if dataset %}
                href="{% url 'tardis_portal.view_dataset' dataset.id %}"
              {% else %}
                href="{% url 'tardis.tardis_portal.views.my_data' %}"
              {% endif %}
            >
              <i class="fa fa-close"></i>
              Cancel
            </a>
            <button type="submit" class="btn btn-primary mr-0">
              <i class="fa fa-check"></i>
              Save
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>  <!-- id=content -->
{% render_bundle 'tardis_portal_add_or_edit_dataset' %}
{% endblock %}

tardis/tardis_portal/templates/tardis_portal/auth_methods.html
{% extends "tardis_portal/portal_template.html" %}
{% load render_bundle from webpack_loader %}

{% block content %}

<input type="hidden" id="csrf-token" value="{{ csrf_token }}">

<p class="alert alert-info">
  This page allows you to link accounts of different authentication method.
</p>

<div id="authList">

{% for userAuth in userAuthMethodList %}
<div class="authMethod" id="authMethod_{{ userAuth.2 }}"
     data-auth-desc="{{ userAuth.1 }}">
  <table class="table table-sm table-bordered">
    <tr>
      <th>Username:</th>
      <td> {{ userAuth.0 }} &nbsp;
      {% if userAuth.1 == 'Local DB' %}
        <a class="edit_auth" id="{{ userAuth.2 }}" href="javascript:void(0);">
          <i class="username-edit-icon fa fa-pencil"></i>
          <i class="username-close-icon fa fa-minus" style="display:none"></i>
        </a>
      {% else %}
        {% if isDjangoAccount %}
          <a class="remove_auth" id="{{ userAuth.2 }}" href="javascript:void(0);">
            <i class="fa fa-remove-circle"></i>
          </a>
        {% endif %}
      {% endif %}
      </td>
    </tr>
    <tr>
      <th>Authentication Method:</th>
      <td>{{ userAuth.1 }}</td>
    </tr>
  </table>
</div> <!-- authMethod -->
{% endfor %}

</div> <!--  authList -->

<div id="authForm">
  {% if supportedAuthMethods|length > 0 %}

    <form id="authForm" action="." method="post" class="form-horizontal">{% csrf_token %}
      <fieldset>
        <legend>Add a new account</legend>
        {% for field in authForm %}
          {{ field }}
        {% endfor %}
      </fieldset>
      <div class="">
        <button type="submit" id="link" class="btn btn-primary">
          Link the Accounts
        </button>
      </div>
    </form>

  {% endif %}
</div> <!-- authForm -->

<div id="template-block" style="display: none">

  <!-- alert-password-changed -->
  <p class="alert-password-changed alert alert-success alert-dismissible">
    <a class="close" data-dismiss="alert">&times;</a>
    Password successfully changed
  </p>

  <p class="alert-error-msg alert alert-danger alert-dismissible">
    <a class="close" data-dismiss="alert">&times;</a>
    <span class="msg"></span>
  </p>

  <div class="form-change-password container">
    <legend>Change Password</legend>
    <form action="." method="post" class="form-horizontal">{% csrf_token %}
      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="id_currentPassword">Current Password</label>
        <div class="col-md-10">
          <input id="id_currentPassword" class="form-control" type="password"
                 name="currentPassword" autocomplete="current-password"
                 style="max-width: 200px;"/>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="id_newPassword">New Password</label>
        <div class="col-md-10">
          <input id="id_newPassword" class="form-control" type="password"
                 name="password" autocomplete="new-password"
                 style="max-width: 200px;" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="id_newPassword1">Confirm Password</label>
        <div class="col-md-10">
          <input id="id_newPassword1" class="form-control" type="password"
                 name="password1" autocomplete="new-password1"
                 style="max-width: 200px;" />
        </div>
      </div>
      <div class="form-group row">
        <div class="offset-md-2 col-md-10">
          <button type="submit" id="edit" class="btn btn-primary" style="max-width: 200px;">
            <i class="fa fa-key"></i>
            Change Password
          </button>
        </div>
      </div>
    </form>
  </div>

  <div class="authMethod">
    <table class="table table-sm table-bordered">
      <tr>
        <th>Username:</th>
        <td><span class="username"></span> &nbsp;
        <a class="remove_auth" href="javascript:void(0);">
          <i class="fa fa-remove-circle"></i>
        </a>
        </td>
      </tr>
      <tr>
        <th>Authentication Method:</th>
        <td><span class="auth-method"></span></td>
      </tr>
    </table>
  </div>
</div>

<script>
var authMethodDict = [];
{% for authKey, authDesc in allAuthMethods.items %}
    authMethodDict["{{ authKey }}"] = "{{ authDesc }}";
{% endfor %}
</script>

{% render_bundle 'tardis_portal_auth_methods' %}

{% endblock content %}

tardis/tardis_portal/templates/tardis_portal/create_experiment.html
{% extends "tardis_portal/portal_template.html" %}
{% load render_bundle from webpack_loader %}
{% load widget_tweaks %}

{% block content %}
<div id="content" class="container">
  <div class="page-header">
    <h1 class="title">{{ subtitle }}</h1>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form id="create_experiment_form" action="" method="POST"
            class="form-horizontal">
        {% csrf_token %}
        <div class="form-group row">
          <label class="col-form-label col-md-2 " for="title">Title</label>
          <div class=" col-md-9 ">
            {{ form.title | add_class:"form-control" }}
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-md-2 " for="authors">Authors</label>
          <div class=" col-md-9 ">
            {{ form.authors | add_class:"form-control" }}
            <p class="help-block mb-0">
                Comma-separated authors and optional emails/URLs
            </p>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-md-2 " for="institution_name">Institution name</label>
          <div class=" col-md-9 ">
           {{ form.institution_name | add_class:"form-control" }}
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-md-2 " for="description">Description</label>
          <div class=" col-md-9 ">
            {{ form.description | add_class:"form-control" }}
          </div>
        </div>
        <div class="form-group row">
          <div class="offset-md-2 col-md-9 text-right">
            <a class="btn btn-outline-secondary"
              {% if experiment_id %}
                href="{% url 'tardis_portal.view_experiment' experiment_id %}"
              {% else %}
                href="{% url 'tardis.tardis_portal.views.my_data' %}"
              {% endif %}
            >
              <i class="fa fa-close"></i>
              Cancel
            </a>
            <button type="submit" class="btn btn-primary mr-0">
              <i class="fa fa-check"></i>
              Save
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
  {% render_bundle 'tardis_portal_create_experiment' %}
</div>
{% endblock %}

tardis/tardis_portal/templates/tardis_portal/manage_group_members.html
{% extends "tardis_portal/portal_template.html" %}
{% load static from staticfiles %}
{% load render_bundle from webpack_loader %}
{% block script %}
{% render_bundle 'tardis_portal_manage_group_members' %}


<input type="hidden" id="csrf-token" value="{{ csrf_token }}">

{% endblock %}

{% block content %}

<!-- create group !-->
<div class="modal" id="modal-create-group" role="dialog" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="title">Create Group</h1>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="alert alert-danger alert-dismissible" style="display:none">
        <button type="button" class="close" onclick="$('.alert').hide()">×</button>
        <div id="error-message"></div>
      </div>

      <div class="loading-placeholder" style="display: none">
        <p>Please wait... <img src="{% static 'images/ajax-loader.gif'%}" alt="loading" /></p>
      </div>

      <div class="modal-body"></div>
    </div>  <!-- class="modal-content" -->
  </div>  <!-- class="modal-dialog" -->
</div>

<!-- create user !-->
<div class="modal" id="modal-create-user" role="dialog" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="title">Create User</h1>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="loading-placeholder" style="display: none">
        <p>Please wait... <img src="{% static 'images/ajax-loader.gif'%}" alt="loading" /></p>
      </div>

      <div class="modal-body"></div>
    </div>  <!-- class="modal-content" -->
  </div>  <!-- class="modal-dialog" -->
</div>

<div class="alert alert-success alert-dismissible" style="display:none">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <strong>Success!</strong>
  <div id="success-message"></div>
</div>

<div class="page-header">
  <h1>Manage Group Members</h1>
</div>

{% if perms.auth.add_group %}
<div class="pull-right">
  <button style="margin-left: 10px;" class="create_group_link btn btn-primary" title="Create Group">
    <i class="fa fa-plus"></i>
    Create Group
  </button>
</div>
{% endif %}
{% if perms.auth.add_user %}
<div class="pull-right">
  <button class="create_user_link btn btn-primary" title="Create User">
    <i class="fa fa-plus"></i>
    Create User
  </button>
</div>
{% endif %}

{% if perms.auth.change_group %}
<div id="grouplist"></div>

<br/>
{% else %}
    <em>You aren't able to view or change groups.</em>
{% endif %}

{% endblock %}

tardis/tardis_portal/templates/tardis_portal/manage_user_account.html
{% extends "tardis_portal/portal_template.html" %}

{% block content %}
<br/>
<div class="container">
 <div class="row">
  <div class="col-md-10">
    <form class="form-horizontal" method="post" action="">{% csrf_token %}
      <div class="form-group row">
        <label class="col-form-label col-md-2 " for="id_first_name">First name</label>
        <div class=" col-md-10 ">
            <input type="text" name="first_name"
                   value="{{ form.first_name.value }}"
                   maxlength="30" class="form-control" id="id_first_name">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-form-label col-md-2 " for="id_last_name">Last name</label>
        <div class=" col-md-10 ">
            <input type="text" name="last_name"
                   value="{{ form.last_name.value }}"
                   maxlength="150" class="form-control" id="id_last_name">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-form-label col-md-2 " for="id_email">Email address</label>
        <div class=" col-md-10 ">
            <input type="email" name="email"
                   value="{{ form.email.value }}"
                   maxlength="254" class="form-control" id="id_email">
        </div>
      </div>
      <div class="form-group row">
        <div class="offset-md-2 col-md-10 text-right">
          <button type="submit" class="btn btn-primary mr-0">
            <i class="fa fa-check"></i>
            Save
          </button>
        </div>
      </div>
    </form>
  </div>
 </div>
</div>
{% endblock %}

tardis/tardis_portal/templates/tardis_portal/pagination.html
{% comment %}Adapted from django/contrib/admin/templates/admin/pagination.html{% endcomment %}
{% load pagination %}
{% if pagination_required %}
  <ul class="pagination justify-content-center">
    {% for page_index in page_range %}
      {% paginator_number data_list paginator page_num query_string page_index %}
    {% endfor %}
  </ul>
{% endif %}

tardis/tardis_portal/templates/tardis_portal/upload_complete.html
<p>Number: {{ numberOfFiles }}</p>
<p>Errors: {{ errorCount }}</p>
<p>Bytes: {{ bytes }}</p>
<p>Speed: {{ speed }}</p>