tardis/apps/related_info/urls.py
from django.conf.urls import url

from .views import index
from .views import list_or_create_related_info
from .views import get_or_update_or_delete_related_info


urlpatterns = [
    url(r'^(?P<experiment_id>\d+)/$', index,
        name='tardis.apps.related_info.views.index'),
    url(r'^experiment/(?P<experiment_id>\d+)/related-info/$',
        list_or_create_related_info,
        name='tardis.apps.related_info.views.list_or_create_related_info'),
    url(r'^experiment/(?P<experiment_id>\d+)/related-info/(?P<ps_id>\d+)$',
        get_or_update_or_delete_related_info,
        name='tardis.apps.related_info.views.get_or_update_or_delete_related_info'),
]

tardis/default_settings/urls.py
ROOT_URLCONF = 'tardis.urls'

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash if there is a path component (optional in other cases).
# Examples: "http://media.lawrence.com", "http://example.com/media/"
MEDIA_URL = ''

# Static content location
STATIC_URL = '/static/'

tardis/tardis_portal/models/instrument.py
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from .facility import Facility


@python_2_unicode_compatible
class Instrument(models.Model):
    '''
    Represents an instrument belonging to a facility that produces data
    '''
    name = models.CharField(max_length=100)
    created_time = models.DateTimeField(null=True, blank=True, default=timezone.now)
    modified_time = models.DateTimeField(null=True, blank=True)
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)

    class Meta:
        app_label = 'tardis_portal'
        verbose_name_plural = 'Instruments'
        unique_together = ['name', 'facility']
        ordering = ('name', )

    # pylint: disable=W0222
    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def getParameterSets(self):
        '''Return the instrument parametersets associated with this
        instrument.
        '''
        from .parameters import Schema
        return self.instrumentparameterset_set.filter(
            schema__type=Schema.INSTRUMENT)

    def _has_change_perm(self, user_obj):
        """
        Instrument objects should only be modified by members of the facility
        managers group.
        """
        return self.facility.manager_group in user_obj.groups.all()

tardis/tardis_portal/forms.py
# -*- coding: utf-8 -*-

#
# Copyright (c) 2010-2011, Monash e-Research Centre
#   (Monash University, Australia)
# Copyright (c) 2010-2011, VeRSI Consortium
#   (Victorian eResearch Strategic Initiative, Australia)
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    *  Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#    *  Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#    *  Neither the name of the VeRSI, the VeRSI Consortium members, nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

'''
forms module

.. moduleauthor::  Gerson Galang <gerson.galang@versi.edu.au>

'''
import logging
import re

from collections import OrderedDict
from collections import UserDict

from django import forms
from django.contrib.sites.shortcuts import get_current_site
from django.forms import ValidationError
from django.forms.utils import ErrorList
from django.forms.models import ModelChoiceField
from django.forms.widgets import HiddenInput
from django.forms import ModelForm
from django.conf import settings
from django.db import transaction
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm

from registration.models import RegistrationProfile

from . import models
from .fields import MultiValueCommaSeparatedField
from .widgets import CommaSeparatedInput
from .models import UserAuthentication, Experiment, License
from .auth.localdb_auth \
    import auth_key as locabdb_auth_key

from .ParameterSetManager import ParameterSetManager

logger = logging.getLogger(__name__)


def getAuthMethodChoices():
    authMethodChoices = ()
    for authMethods in settings.AUTH_PROVIDERS:
        authMethodChoices += ((authMethods[0], authMethods[1]),)
    return authMethodChoices


attrs_dict = {'class': 'required'}


class LoginForm(AuthenticationForm):
    # authMethod = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'] = forms.CharField(required=True,
                                                  label="Username",
                                                  max_length=75)


class RegistrationForm(forms.Form):
    """
    Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.

    """

    username = forms.RegexField(
        regex=r'^[\w\.]+$',
        max_length=30,
        widget=forms.TextInput(attrs=attrs_dict),
        label=_("Username"),
        error_messages={'invalid':
                        _("This value must contain only letters, \
                        numbers and underscores.")})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("Email address"))

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
        label=_("Password"))

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
        label=_("Password (again)"))

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        username = '%s' % self.cleaned_data['username']

        try:
            User.objects.get(username__iexact=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            _("A user with that username already exists."))

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """
        if 'password1' in self.cleaned_data and \
                'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != \
                    self.cleaned_data['password2']:
                raise forms.ValidationError(
                    _("The two password fields didn't match."))

        return self.cleaned_data

    @transaction.atomic
    def save(self, profile_callback=None):
        user = RegistrationProfile.objects.create_inactive_user(
            site=get_current_site(None),
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password1'],
            email=self.cleaned_data['email'])

        authentication = UserAuthentication(
            userProfile=user.userprofile,
            username=self.cleaned_data['username'],
            authenticationMethod=locabdb_auth_key)
        authentication.save()

        return user


class AddUserPermissionsForm(forms.Form):

    entered_user = forms.CharField(
        label='User', required=False, max_length=100)
    autocomp_user = forms.CharField(
        label='', required=False, max_length=100, widget=forms.HiddenInput)
    authMethod = forms.CharField(
        required=True, widget=forms.Select(choices=getAuthMethodChoices()),
        label='Authentication Method')
    read = forms.BooleanField(
        label='Read access', required=False, initial=True)
    read.widget.attrs['class'] = 'canRead'
    write = forms.BooleanField(label='Edit access', required=False)
    write.widget.attrs['class'] = 'canWrite'
    delete = forms.BooleanField(label='', required=False,
                                widget=forms.HiddenInput)
    delete.widget.attrs['class'] = 'canDelete'


class ManageGroupPermissionsForm(forms.Form):

    authMethod = forms.CharField(
        required=True,
        widget=forms.Select(choices=getAuthMethodChoices()),
        label='Authentication Method')
    adduser = forms.CharField(label='User', required=False, max_length=100)
    adduser.widget.attrs['class'] = 'usersuggest'
    admin = forms.BooleanField(
        label='Group Admin', required=False, initial=False)
    admin.widget.attrs['class'] = 'isAdmin'


class CreateUserPermissionsForm(RegistrationForm):
    authMethod = forms.CharField(
        required=True,
        widget=forms.Select(choices=getAuthMethodChoices()),
        label='Authentication Method')


def createLinkedUserAuthenticationForm(authMethods):
    """Create a LinkedUserAuthenticationForm and use the contents of
    authMethods to the list of options in the dropdown menu for
    authenticationMethod.

    """
    _authenticationMethodChoices = ()
    for authMethodKey in authMethods.keys():
        _authenticationMethodChoices += (
            (authMethodKey, authMethods[authMethodKey]), )

    fields = {}
    fields['authenticationMethod'] = forms.CharField(
        label='Authentication Method',
        widget=forms.Select(choices=_authenticationMethodChoices),
        required=True)
    fields['username'] = forms.CharField(
        label='Username', max_length=75, required=True)
    fields['password'] = forms.CharField(
        required=True, widget=forms.PasswordInput(),
        label='Password')

    return type('LinkedUserAuthenticationForm', (forms.BaseForm, ),
                {'base_fields': fields})


class ImportParamsForm(forms.Form):

    username = forms.CharField(max_length=400, required=True)
    password = forms.CharField(max_length=400, required=True)
    params = forms.FileField()


class RegisterExperimentForm(forms.Form):

    username = forms.CharField(max_length=400, required=True)
    password = forms.CharField(max_length=400, required=True)
    xmldata = forms.FileField(required=False)
    xml_filename = forms.CharField(max_length=400, required=False)
    experiment_owner = forms.CharField(max_length=400, required=False)
    originid = forms.CharField(max_length=400, required=False)
    from_url = forms.CharField(max_length=400, required=False)


class DatasetForm(forms.ModelForm):

    description = forms.CharField()

    class Meta:
        model = models.Dataset
        fields = [
            'description',
            'directory',
            'instrument',
        ]


class ExperimentAuthor(forms.ModelForm):

    class Meta:
        model = models.ExperimentAuthor
        fields = [
            'author',
            'institution',
            'email',
            'order',
            'url',
        ]


class ExperimentForm(forms.ModelForm):
    """
    This handles the complex experiment forms.

tardis/tardis_portal/views/ajax_actions.py
# pylint: disable=http-response-with-json-dumps,http-response-with-content-type-json
"""
views that perform some action and don't return anything very useful
"""

import json
import logging

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.http import HttpResponse
from django.views.decorators.cache import never_cache

from celery import group, chord

from ..auth import decorators as authz
from ..models import Dataset
from ..tasks import cache_done_notify

logger = logging.getLogger(__name__)


@never_cache
@authz.dataset_download_required
def cache_dataset(request, dataset_id=None, notify=True):
    dataset = Dataset.objects.get(id=dataset_id)
    run_this = group(df.cache_file.s()
                     for df in dataset.datafile_set.all())
    if notify:
        run_this = chord(run_this)(
            cache_done_notify.subtask(kwargs={
                'priority': settings.DEFAULT_EMAIL_TASK_PRIORITY,
                'user_id': request.user.id,
                'site_id': Site.objects.get_current(request).id,
                'ct_id': ContentType.objects.get_for_model(Dataset).id,
                'obj_ids': [dataset_id], }))
    if hasattr(run_this, 'apply_async'):
        result = run_this.apply_async()
    else:
        result = run_this
    return HttpResponse(json.dumps({"result": str(result.id)}),
                        content_type='application/json')

tardis/tardis_portal/views/images.py
"""
views that return images or route to images
"""

from base64 import b64decode
import logging
from os import path

from django.conf import settings
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.views.decorators.cache import never_cache

from ..auth import decorators as authz
from ..models import ExperimentParameter, DatasetParameter, \
    DatafileParameter, Dataset
from ..shortcuts import return_response_error

logger = logging.getLogger(__name__)


@never_cache
def load_image(request, parameter):
    file_path = path.abspath(path.join(settings.METADATA_STORE_PATH,
                                       parameter.string_value))

    from wsgiref.util import FileWrapper
    try:
        wrapper = FileWrapper(open(file_path, 'rb'))
    except IOError:
        return HttpResponseNotFound()
    return HttpResponse(wrapper, content_type=parameter.name.units)


def load_experiment_image(request, parameter_id):
    parameter = ExperimentParameter.objects.get(pk=parameter_id)
    experiment_id = parameter.parameterset.experiment.id
    if authz.has_experiment_access(request, experiment_id):
        return load_image(request, parameter)
    return return_response_error(request)


def load_dataset_image(request, parameter_id):
    parameter = DatasetParameter.objects.get(pk=parameter_id)
    dataset = parameter.parameterset.dataset
    if authz.has_dataset_access(request, dataset.id):
        return load_image(request, parameter)
    return return_response_error(request)


def load_datafile_image(request, parameter_id):
    try:
        parameter = DatafileParameter.objects.get(pk=parameter_id)
    except DatafileParameter.DoesNotExist:
        return HttpResponseNotFound()
    datafile = parameter.parameterset.datafile
    if authz.has_datafile_access(request, datafile.id):
        return load_image(request, parameter)
    return return_response_error(request)


@authz.experiment_access_required
def display_experiment_image(
        request, experiment_id, parameterset_id, parameter_name):

    # TODO handle not exist

    if not authz.has_experiment_access(request, experiment_id):
        return return_response_error(request)

    image = ExperimentParameter.objects.get(name__name=parameter_name,
                                            parameterset=parameterset_id)

    return HttpResponse(b64decode(image.string_value), content_type='image/jpeg')


@authz.dataset_access_required
def display_dataset_image(
        request, dataset_id, parameterset_id, parameter_name):

    # TODO handle not exist

    if not authz.has_dataset_access(request, dataset_id):
        return return_response_error(request)

    image = DatasetParameter.objects.get(name__name=parameter_name,
                                         parameterset=parameterset_id)

    return HttpResponse(b64decode(image.string_value), content_type='image/jpeg')


@authz.datafile_access_required
def display_datafile_image(
        request, datafile_id, parameterset_id, parameter_name):

    # TODO handle not exist

    if not authz.has_datafile_access(request, datafile_id):
        return return_response_error(request)

    image = DatafileParameter.objects.get(name__name=parameter_name,
                                          parameterset=parameterset_id)

    return HttpResponse(b64decode(image.string_value), content_type='image/jpeg')



@authz.dataset_access_required
def dataset_thumbnail(request, dataset_id):
    dataset = Dataset.objects.get(id=dataset_id)
    tn_url = dataset.get_thumbnail_url()
    if tn_url is None:
        return HttpResponseNotFound()
    return HttpResponseRedirect(tn_url)

tardis/tardis_portal/templates/tardis_portal/ajax/add_user_result.html
<div class="access_list_user row" style="margin-top: 1ex; margin-bottom: 1ex">
  <div class="col-md-5">
    <strong>{{ user.first_name }} {{ user.last_name }} [{{ user.username }}]</strong>
    {% if user.email %}<em>({{ user.email }})</em>{% endif %}
  </div>
  <div class="col-md-4">
    {% if user_acl.canRead %}
    <span class="badge badge-success">Read</span>
    {% endif %}
    {% if user_acl.canWrite %}
    <span class="badge badge-success">Edit</span>
    {% endif %}
    {% if user_acl.isOwner %}
    <span class="badge badge-info">Owner</span>
    {% endif %}
  </div>
  <div class="col-md-3">
    <a title="Remove Access" class="remove_user btn btn-danger btn-sm"
      href="{% url 'tardis.tardis_portal.views.remove_experiment_access_user' experiment_id user.username %}">
      Delete
    </a>
  </div>
</div> <!-- access_list_user -->

tardis/tardis_portal/templates/tardis_portal/ajax/add_user_to_group_result.html
<div class="access_list_user row" style="margin-top: 1ex; margin-bottom: 1ex">
  <div class="col-md-6">
    <strong>{{ user.first_name }} {{ user.last_name }} [{{ user.username }}]</strong>
    {% if user.email %}<em>({{ user.email }})</em>{% endif %}
  </div>
  <div class="col-md-2">
    {% if user in group_admins %}
      <span class="label label-success">Group Admin</span>
    {% else %}
      <span class="label label-info">Member</span>
    {% endif %}
  </div>
  <div class="col-md-2">
    <button
       type="button"
       title="Remove Access" class="remove_user btn btn-danger btn-sm"
       data-group_id="{{group_id}}"
       href="{% url 'tardis.tardis_portal.views.remove_user_from_group' group_id user.username %}">
      <i class="fa fa-trash"></i>
      Delete
    </button>
  </div>
</div> <!-- access_list_user -->

tardis/tardis_portal/templates/tardis_portal/ajax/choose_rights.html
{% load static from staticfiles %}
{% block content %}
{% load render_bundle from webpack_loader %}
{% load widget_tweaks %}
<!-- Scripts -->
{% load jstemplate %}
{% mustachejs "tardis_portal/license_selector" %}
{% mustachejs "tardis_portal/rights_update_message" %}
{% mustachejs "tardis_portal/ajax_error" %}

<!-- Success / Error Message -->
<div id="choose-rights-message"></div>

<!-- Selection form -->
<h3>Step 1: Change Public Access:</h3>
<br/>
<form action="{% url 'tardis.tardis_portal.views.choose_rights' experiment.id %}"
      method="post" class="experiment-rights form-horizontal">{% csrf_token %}

  {{ form.license }} {# hidden input #}
  {{ form.legal_text }} {# hidden input #}
  <div class="form-group">
    <label class="col-form-label col-md-3 " for="id_public_access">Public access</label>
    <div class="col-md-9 ">
      {{ form.public_access | add_class:"form-control" }}
    </div>
  </div>

  <h3>Step 2: Select a license:</h3>
  <div id="license-options"></div>
  <div id="selected-license-text"></div>
  <div id="legal-section">
    <button class="btn-secondary" id="reselect-license">Reselect License</button>
    <br/><br/>
    <h3 >Step 3: Accept The Legal Agreement:</h3>
    <pre id="publishing-legal-text"
         style="white-space: pre-wrap; word-break: keep-all;">{{ form.legal_text.value }}</pre>
    <div class="checkbox">
      <label>
        <input id="publishing-consent" type="checkbox" required value="Agree" />
        I agree to the above terms
      </label>
    </div>
  </div>
  <br>
  <div id="confirm-license-btn-group" class="form-group text-right">
    <button type="button" class="cancel-button btn btn-outline-secondary"
            data-dismiss="modal">
      <i class="fa fa-close"></i>
      Cancel
    </button>
    <button type="button" class="submit-button btn btn-primary">
      <i class="fa fa-check"></i>
      Confirm
    </button>
  </div>
</form>
{% endblock %}

tardis/tardis_portal/templates/tardis_portal/ajax/experiment_dataset_transfer.html
<input type="hidden" id="experiment-id" value="{{ experiment.id }}">
{% if experiments %}

<form id="other-experiment-selection" class="form-horizontal">{% csrf_token %}
  <fieldset>
    <div class="form-group">
      <label class="col-md-2 col-form-label" for="input01">Experiment</label>
      <div class="col-md-10">
        <select class="form-control" name="experiment_id">
          {% for experiment in experiments %}
          <option value="{{experiment.id}}">{{experiment.title}}</option>
          {% endfor %}
        </select>
      </div>
    </div>
  </fieldset>
</form>

<p class="help-text">
  <strong>Instructons:</strong> Using the above list, select an experiment to copy from,
  then drag datasets to the right to associate them with the current experiment.
</p>

<div id="other-experiment-datasets"></div>

{% else %}
<div class="alert">
  <p>You do not currently own any other experiments.</p>
</div>
{% endif %}

tardis/tardis_portal/templates/tardis_portal/ajax/experiment_description.html
<div id="experiment_description"
    class="container-fluid">

  {% load capture %}

  {% block handle %}
  {% if experiment.handle %}
  <dl class="row">
    <dt class="col-sm-3">Persistent Handle:</dt>
    <dd class="col-sm-9">
      <a href="http://hdl.handle.net/{{ experiment.handle }}">
        {{ experiment.handle }}
      </a>
    </dd>
  </dl>
  {% endif %}
  {% endblock handle %}

  {% block institution %}
  {% if experiment.institution_name %}
  <dl class="row">
    <dt class="col-sm-3">Institution</dt>
    <dd class="col-sm-9" property="dc:publisher">
      {{experiment.institution_name}}
    </dd>
  </dl>
  {% endif %}
  {% endblock institution %}

  {% block start_end_time %}
  {% if experiment.start_time and experiment.end_time %}
  <dl class="row">
    <dt class="col-sm-3">Date</dt>
    <dd class="col-sm-9">{{ experiment.start_time }} - {{ experiment.end_time }}</dd>
  </dl>
  {% endif %}
  {% endblock start_end_time %}

  {% block license %}
  <dl class="row">
    <dt class="col-sm-3">Licensing</dt>
    <dd class="col-sm-9">
      {% if experiment.license_id %}
        <div class="row">
          <div class="col-md-6">
            This experiment data is licensed under
            <a rel="license"
               property="dc:license"
               href="{{ experiment.license.url }}">
              {{ experiment.license.name }}</a>.
          </div>
          {% if experiment.license.image_url != None %}
          <div class="col-md-6">
            <img src="{{ experiment.license.image_url }}"/>
          </div>
          {% endif %}
        </div>
      {% else %}
        <abbr title="All rights reserved">
          Unspecified
        </abbr>
      {% endif %}
    </dd>
  </dl>
  {% endblock license %}

  {% block extra_info %}
  {% endblock extra_info %}

  {% block extra_content %}
  {% endblock extra_content %}

  {% block experiment_admin %}
      {% block experiment_owners %}
      {% if experiment.get_owners %}
      <dl class="row">
        <dt class="col-sm-3">Administrators</dt>
        {% for owner in experiment.get_owners %}
          <dd class="col-sm-9">
          {% capture as owner_text %}
            {% if owner.first_name and owner.last_name %}
              <span class="experiment-owner" title="{{ owner.username }}">
                {{ owner.first_name }} {{ owner.last_name }}
              </span>
            {% else %}
              {{ owner.username }}
            {% endif %}
          {% endcapture %}
          {{owner_text}}
          </dd>
        {% endfor %}
      </dl>
      {% endif %}
      {% endblock experiment_owners %}
  {% endblock experiment_admin %}

  {% block downloads %}
  {% if has_download_permissions %}
  <dl class="row download_entire_experiment">
    <dt class="col-sm-3">Download All</dt>
    <dd class="col-sm-9">
      {% if organization|length > 1 %}
      {% for p in protocol %}
        {% for o in organization %}
          <a class="btn btn-outline-secondary btn-sm" href="{{p.1}}{{o}}"
             title="Download Entire Experiment as {{p.0|upper}} with {{o}} organization">
            <i class="fa fa-download"></i>
            {% if o == default_organization %}
            {{p.0|upper}}
            {% else %}
            {{p.0|upper}} - {{o}}
            {% endif %}
          </a>
        {% endfor %}
      {% endfor %}
    {% else %}
      {% for p in protocol %}
        <a class="btn btn-outline-secondary btn-sm" href="{{p.1}}"
           title="Download Entire Experiment as {{p.0|upper}}">
          <i class="fa fa-download"></i>
          {{p.0|upper}}
        </a>
      {% endfor %}
    {% endif %}
      <a href="{% url "tardis.apps.sftp:index" %}?object_id={{ experiment.id }}&object_type=experiment"
         target="_blank" class="btn btn-outline-secondary btn-sm" title="Download with SFTP">
        <i class="fa fa-download"></i>
        SFTP
      </a>
    </dd>
  </dl>
  {% endif %}
  {% endblock downloads %}

</div>

tardis/tardis_portal/templates/tardis_portal/ajax/experiment_metadata.html
{% load capture %}

<div class="container-fluid">
  <div class="float-right">
    {% if has_write_permissions and not experiment.locked and not experiment.is_publication %}
        <a title="Add" class="add-metadata btn btn-outline-secondary btn-sm"
           href="{% url 'tardis.tardis_portal.views.add_experiment_par' experiment.id %}">
          <i class="fa fa-plus"></i>
          Add Experiment Metadata
        </a>
    {% endif %}
  </div>
</div>

<br />
{% for parameterset in parametersets %}
  {% capture as edit_control %}
   {% if has_write_permissions and not parameterset.schema.immutable %}
   <div class="pull-right">
       <a class="edit-metadata btn btn-sm btn-outline-secondary"
          href="{% url 'tardis.tardis_portal.views.edit_experiment_par' parameterset.id %}">
          <i class="fa fa-pencil"></i>
          Edit
       </a>
   </div>
   {% endif %}
  {% endcapture %}
    <div style="margin-top: 10px">
        {% include "tardis_portal/ajax/parameter_table.html" with parameters=parameterset.experimentparameter_set.all %}
    </div>
{% empty %}
  <div class="alert alert-info mt-3" >
    There is no metadata for this experiment.
  </div>
{% endfor %}

tardis/tardis_portal/templates/tardis_portal/ajax/group_user_list.html
<div class="users w-66">
  <div class="alert alert-danger alert-dismissible" style="display: none;">
    <button type="button" class="close" data-hide="alert">×</button>
    <span class="message">You cannot remove yourself from this group.</span>
  </div>
{% for user in users %}
  {% include "tardis_portal/ajax/add_user_to_group_result.html" %}
{% endfor %}
</div> <!-- users -->
<form class="add-user-form form-horizontal" novalidate>
  <legend>Add User</legend>
  <div class="form-group row">
    <label class="col-form-label col-md-2 " for="id_adduser">User</label>
      <div class="col-md-4" style="max-width: 250px;">
        <input type="text" name="adduser" id="id_adduser-{{group_id}}" required
               class="usersuggest form-control"
               maxlength="100" autocomplete="off">
        <div class="invalid-feedback"></div>
      </div>
  </div>

  <div class="form-group row">
    <div class=" offset-md-2 col-md-4">
      <div class="checkbox">
        <label>
          <input type="checkbox" name="admin" class="isAdmin" id="id_admin-{{group_id}}"> <span>Group Admin</span>
        </label>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <div class="offset-md-2 col-md-4">
      <input type="hidden" name="group_id" class="group_id" value="{{group_id}}">
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-plus"></i>
        Add User to Group
      </button>
    </div>
  </div>
</form>

tardis/tardis_portal/templates/tardis_portal/ajax/parameter_set_unavailable.html
<p>
No schemas are available to add metadata.
</p>