tardis/apps/related_info/urls.py
from django.conf.urls import url

from .views import index
from .views import list_or_create_related_info
from .views import get_or_update_or_delete_related_info


urlpatterns = [
    url(r'^(?P<experiment_id>\d+)/$', index,
        name='tardis.apps.related_info.views.index'),
    url(r'^experiment/(?P<experiment_id>\d+)/related-info/$',
        list_or_create_related_info,
        name='tardis.apps.related_info.views.list_or_create_related_info'),
    url(r'^experiment/(?P<experiment_id>\d+)/related-info/(?P<ps_id>\d+)$',
        get_or_update_or_delete_related_info,
        name='tardis.apps.related_info.views.get_or_update_or_delete_related_info'),
]

tardis/apps/sftp/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

app_name = "tardis.apps.sftp"
urlpatterns = [
    url(r'^cyberduck/connection.png$',
         views.cybderduck_connection_window,
         name='cyberduck_connection_window'),
    url(r'^$', views.sftp_access, name='index'),
    url(r'^keys/$', views.sftp_keys, name='sftp_keys'),
]

tardis/default_settings/urls.py
ROOT_URLCONF = 'tardis.urls'

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash if there is a path component (optional in other cases).
# Examples: "http://media.lawrence.com", "http://example.com/media/"
MEDIA_URL = ''

# Static content location
STATIC_URL = '/static/'

tardis/apps/sftp/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class SFTPPublicKey(models.Model):
    """Model for associated SFTP public keys with users

    :param user: user who owns this public key
    :type user: ForeignKey for User
    :param name: name for this public key
    :type name: string
    :param public_key: OpenSSH formatted public key
    :type public_key: string
    :param added: date the public key was added (Optional)
    :type added: date
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('Device name', max_length=256)
    key_type = models.CharField("Key Type", max_length=100)
    public_key = models.TextField('Public Key')
    added = models.DateField("Added", auto_now_add=True)

    def __str__(self):
        return str(self.user) + ": " + self.name

tardis/apps/sftp/forms.py
# -*- coding: utf-8 -*-

import base64

from django import forms
from django.utils.translation import ugettext as _
from paramiko import RSAKey, DSSKey, ECDSAKey
from paramiko.ssh_exception import SSHException
from tastypie.validation import FormValidation


class KeyAddForm(forms.Form):
    name = forms.CharField(required=True, max_length=256)
    key_type = forms.CharField(required=True, max_length=100)
    public_key = forms.CharField(required=True, widget=forms.Textarea)

    def clean(self):
        data = super().clean()
        key_type = data.get('key_type')
        public_key = data.get('public_key')

        try:
            if key_type == "ssh-rsa":
                k = RSAKey(data=base64.b64decode(public_key))
            elif key_type == "ssh-dss":
                k = DSSKey(data=base64.b64decode(public_key))
            elif key_type.startswith('ecdsa'):
                k = ECDSAKey(data=base64.b64decode(public_key))
            else:
                raise forms.ValidationError(
                    _("Unsupport key type: %(keytype)s"),
                    code='invalid keytype',
                    params={'key_type': key_type}
                )

            data['key_type'] = k.get_name()
            data['public_key'] = k.get_base64()

        except (TypeError, SSHException, UnicodeDecodeError) as err:
            if len(public_key) > 30:
                body = public_key[0:30]
            else:
                body = public_key

            raise forms.ValidationError(
                _("Body of SSH public key is invalid:\n%(body)s\n"
                  "Error: %(err)s"),
                code='invalid key body',
                params={'body': body + "...", 'err': err}
            )

        return data


key_add_form = FormValidation(form_class=KeyAddForm)


class KeyGenerateForm(forms.Form):
    name = forms.CharField(required=True, max_length=256)

tardis/apps/sftp/views.py
# -*- coding: utf-8 -*-

import io
import json
from os import path
from wsgiref.util import FileWrapper

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.forms.forms import NON_FIELD_ERRORS
from django.http import (
    HttpResponse,
    HttpResponseServerError,
    StreamingHttpResponse
)
from django.shortcuts import render
from paramiko import RSAKey
from paramiko.ssh_exception import SSHException
from PIL import Image, ImageFont, ImageDraw

from tardis.tardis_portal.auth.decorators import has_experiment_download_access
from .forms import KeyGenerateForm
from .models import SFTPPublicKey


@login_required
def sftp_access(request):
    """
    Show dynamically generated instructions on how to connect to SFTP
    :param Request request: HttpRequest
    :return: HttpResponse
    :rtype: HttpResponse
    """
    from tardis.tardis_portal.download import make_mapper
    object_type = request.GET.get('object_type')
    object_id = request.GET.get('object_id')
    sftp_start_dir = ''
    if object_type and object_id:
        ct = ContentType.objects.get_by_natural_key(
            'tardis_portal', object_type)
        item = ct.model_class().objects.get(id=object_id)
        if object_type == 'experiment':
            exps = [item]
            dataset = None
            datafile = None
        else:
            if object_type == 'dataset':
                dataset = item
                datafile = None
            elif object_type == 'datafile':
                datafile = item
                dataset = datafile.dataset
            exps = dataset.experiments.all()
        allowed_exps = []
        for exp in exps:
            if has_experiment_download_access(request, exp.id):
                allowed_exps.append(exp)
        if allowed_exps:
            path_mapper = make_mapper(settings.DEFAULT_PATH_MAPPER,
                                      rootdir=None)
            exp = allowed_exps[0]
            path_parts = ['/home', request.user.username, 'experiments',
                          path_mapper(exp)]
            if dataset is not None:
                path_parts.append(path_mapper(dataset))
            if datafile is not None:
                path_parts.append(datafile.directory)
            sftp_start_dir = path.join(*path_parts)

    if request.user.userprofile.isDjangoAccount:
        sftp_username = request.user.username
    else:
        login_attr = getattr(settings, 'SFTP_USERNAME_ATTRIBUTE', 'email')
        sftp_username = getattr(request.user, login_attr)
    c = {
        'sftp_host': request.get_host().split(':')[0],
        'sftp_port': getattr(settings, 'SFTP_PORT', 2200),
        'sftp_username': sftp_username,
        'sftp_start_dir': sftp_start_dir,
        'site_name': getattr(settings, 'SITE_TITLE', 'MyTardis'),
    }
    c['sftp_url'] = 'sftp://{}@{}:{}{}'.format(
        c['sftp_username'],
        c['sftp_host'],
        c['sftp_port'],
        c['sftp_start_dir'])
    return render(request, template_name='sftp/index.html', context=c)


@login_required
def cybderduck_connection_window(request):
    base_image = ("tardis/apps/sftp/images/cyberduck_connection_blank.png")
    font_file = "tardis/apps/sftp/fonts/roboto.ttf"
    base = Image.open(base_image)
    font = ImageFont.truetype(font_file, 22)
    draw = ImageDraw.Draw(base)

    if request.user.userprofile.isDjangoAccount:
        sftp_username = request.user.username
    else:
        login_attr = getattr(settings, 'SFTP_USERNAME_ATTRIBUTE', 'email')
        sftp_username = getattr(request.user, login_attr)

    sftp_host = request.get_host().split(':')[0]
    sftp_port = str(getattr(settings, 'SFTP_PORT', 2200))
    info = [
        {'location': (532, 322),
         'text': sftp_host},
        {'location': (1096, 322),
         'text': sftp_port},
        {'location': (532, 420),
         'text': sftp_username},
    ]
    url = {'location': (532, 370),
           'text': 'sftp://{}@{}:{}/'.format(
               sftp_username,
               sftp_host,
               sftp_port)}
    for text in info:
        draw.text(text['location'], text['text'], font=font,
                  fill=(0, 0, 0))

    def draw_underlined_text(draw, pos, text, font, **options):
        twidth, theight = draw.textsize(text, font=font)
        lx, ly = pos[0], pos[1] + theight - 2
        draw.text(pos, text, font=font, **options)
        draw.line((lx, ly, lx + twidth - 2, ly), **options)

    url_font = ImageFont.truetype(font_file, 18)
    url_colour = (0, 49, 249)
    draw_underlined_text(draw, url['location'],
                         url['text'], url_font, fill=url_colour)
    response = HttpResponse(content_type='image/png')
    base.save(response, "PNG")
    base.save("foo.png")
    return response


@login_required
def sftp_keys(request):
    """Generate an RSA key pair for a user.

    Generates a key pair, stores the public part of the key and provides a one
    time opportunity for the user to download the private part of the key.

    :param request: http request
    :type request: HttpRequest
    :return: either returns form on GET request or private key download on POST
        request
    :rtype: HttpResponse
    """
    if request.method == "POST":
        form = KeyGenerateForm(request.POST)
        if form.is_valid():
            user = request.user
            key_name = form.cleaned_data["name"]
            key = RSAKey.generate(4096)
            key_file = io.StringIO()
            try:
                key.write_private_key(key_file)
            except (IOError, SSHException):
                return HttpResponseServerError(
                    json.dumps({
                        "error": "Oops! Failed to generate key. "
                        "Please try again later."
                    }),
                    content_type="application/json"
                )
            else:
                # Create SFTPPublicKey record
                SFTPPublicKey.objects.create(
                    user=user,
                    name=key_name,
                    key_type=key.get_name(),
                    public_key=key.get_base64()
                )

                # Move to beginning of file and stream HTTPReponse
                key_file.seek(0)
                response = StreamingHttpResponse(
                    FileWrapper(key_file),
                    content_type="application/octet-stream"
                )
                response["Content-Disposition"] =\
                    "attachment; filename='{}'".format(key_name)

                return response
    else:
        form = KeyGenerateForm()

        enable_generate = False
        if getattr(settings, "REQUIRE_SSL_TO_GENERATE_KEY", True):
            enable_generate = request.is_secure()
        else:
            enable_generate = True

        if not enable_generate:
            form.fields['name'].disabled = True
            form.errors[NON_FIELD_ERRORS] = form.error_class([
              "The SSH key generation feature has been disabled because your "\
              "connection is insecure. Please contact your %s service administrator "\
              "about securing your connection." % getattr(settings, "SITE_TITLE", "MyTardis")
            ])

    return render(
        request,
        'sftp/keys.html',
        {
            'form': form,
            'enable_generate': enable_generate
        }
    )

tardis/apps/sftp/templates/sftp/index.html
{% extends "tardis_portal/portal_template.html" %}
{% block content %}
    <h1>Instructions for file access via SFTP and SSHFS</h1>
    <div class="row">
    <div class="col-md-8">
    <p>
      You can access all the files you have access to on the web via the SFTP protocol.
      This allows you to use Desktop programs like Filezilla or <a href="https://cyberduck.io"
      target="_blank">Cyberduck</a> to browse and download your files. On some systems you can
      also mount MyTardis as a drive using SSHFS. Instructions for accessing {{ site_name }} via
      SFTP are given below.
    </p>
    <p>
      <b>Note:</b> You must register your public SSH key in {{ site_name }} first.
      Proceed <a href="{% url "tardis.apps.sftp:sftp_keys" %}">here</a> to register and
      manage your SSH keys.
    </p>

    <h2>Magic URL</h2>
    <p>Some systems are configured in a way that this link will connect you
        automatically:<br/><a href="{{ sftp_url }}">{{ sftp_url }}</a></p>

    <h2>SFTP access parameters</h2>
    <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Parameter</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Host</td>
        <td>{{ sftp_host }}</td>
      </tr>
      <tr>
        <td>Port</td>
        <td>{{ sftp_port }}</td>
      </tr>
      <tr>
        <td>Username</td>
        <td>{{ sftp_username }}</td>
      </tr>
      <tr>
        <td>Password</td>
        <td><i>Leave this blank</i></td>
      </tr>
      <tr>
        <td>SSH Private Key</td>
        <td>Specify the path to your SSH private key.</td>
      </tr>
      <tr>
        <td>Start folder</td>
        <td>{{ sftp_start_dir }}</td>
      </tr>
    </tbody>
    </table>

        <h2>Cyberduck example</h2>
        <p>Get Cyberduck here: <a
            href="https://cyberduck.io"
            target="_blank">https://cyberduck.io</a> </p>
        <p>Hit "Open Connection" and enter your details (Start folder is under
            'More Options')<br/>
            Make sure the top dropdown menu reads SFTP<br/>
            <img src="{% url "tardis.apps.sftp:cyberduck_connection_window" %}"
	         alt="Cyberduck connection window"/>
        </p>
{#        <h2>SSHFS on Linux</h2>#}

    </div>
</div>
{% endblock content %}

tardis/apps/sftp/templates/sftp/keys.html
{% extends "tardis_portal/portal_template.html" %}
{% load static from staticfiles %}

{% block script %}
<script  type="text/javascript" src="{% static 'js/sftp/sftp.js' %}"></script>
{% endblock script %}

{% block style %}
<link href="{% static 'css/sftp/sftp.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="col-md-8">
  <h2>SSH Keys</h2>
  <p>Add and manage your public SSH keys for accessing {{site_title|default:'MyTardis'}} via SFTP.</p>
  <div class="row">
    <div class="ml-auto" style="margin: 0px 0px 10px 10px;">
      <a class="btn btn-outline-secondary" data-toggle="modal" href="#keyGenerateModal">
        <i class="fa fa-plus"></i>
        <span>Generate key</span>
      </a>
    </div>
    <div style="margin: 0px 0px 10px 10px;">
      <a class="btn btn-outline-secondary" data-toggle="modal" href="#keyAddModal">
        <i class="fa fa-plus"></i>
        <span>Add key</span>
      </a>
    </div>
  </div>
  <div class="row">
    {# Note: This table is loaded via AJAX. Check sftp.loadKeyTable() method in static/js/sftp/sftp.js #}
    <div id='keyTable'>
      <span><i class="fa fa-2x fa-spinner fa-pulse"></i> Loading keys...</span>
    </div>
  </div>
</div>

<div class="modal" id="keyAddModal" role="dialog" tabindex="-1">
  <div class="modal-dialog modal-lg" role="document">
    <form id="keyAddForm" class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Add SSH Keys</h3>
        <button type="button" class="close" data-dismiss="modal" onclick="sftp.clearKeyAddForm()">×</button>
      </div>
      <div class="modal-body">
        <div>
          <span>Add your own public SSH Key using the form below.</span>
          <span><b>Important:</b> Don't add your private key.</span>
        </div>
        <div class="form-group mt-1">
          <label for="keyName">Device Name:</label>
          <input type="text" id="keyName" class="form-control" name="name">
        </div>
        <div class="form-group">
          <label for="key">Public Key:</label>
          <textarea id="key" class="form-control" rows="6" name="public_key"></textarea>
        </div>
        <div class="form-group">
          <div id="keyAddAlert" class="alert alert-danger" style="display: none;">
            <div id="keyAddAlertMessage"></div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-outline-secondary" style="margin: 0px 0px 10px 10px;" data-dismiss="modal" onclick="sftp.clearKeyAddForm();return false;">
          <i class="fa fa-close"></i>
          Close
        </button>
        <button class="btn btn-primary" style="margin: 0px 0px 10px 10px;" onclick="sftp.addKey();return false;">
          <i class="fa fa-plus"></i>
          Add Key
        </button>
      </div>
    </form>  <!-- class="modal-content" -->
  </div>  <!-- class="modal-dialog" -->
</div>

<div class="modal" id="keyGenerateModal" role="dialog" tabindex="-1">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Generate an SSH key pair</h3>
        <button type="button" class="close" data-dismiss="modal" onclick="sftp.clearKeyGenerateForm()">×</button>
      </div>
      <div class="modal-body">
        <p>{{site_title|default:'MyTardis'}} can generate an SSH key pair for you. Only the public part of the key pair will be stored by {{site_title|default:'MyTardis'}} and you will be provided with a one time opportunity to download the private part of the key pair.</p>
        <br>
        <form id="keyGenerateForm" action="{% url 'tardis.apps.sftp:sftp_keys' %}" method="post">
          {% if enable_generate %}
          {% else %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              The SSH key generation feature has been disabled because your connection is insecure.
              Please contact your MyTardis service administrator about securing your connection.
	      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	      </button>
            </div>
          {% endif %}
          <div class="form-group">
            <label class="col-form-label" for="id_name">Name</label>
            <div class=" ">
              {% if enable_generate %}
                <input type="text" name="name" maxlength="256" class="form-control" required="required" id="id_name">
              {% else %}
                <input type="text" name="name" maxlength="256" class="form-control" disabled required="" id="id_name">
              {% endif %}
            </div>
          </div>
          {% if enable_generate %}
            <button type="submit" class="btn btn-outline-secondary">
          {% else %}
            <button type="submit" class="btn btn-outline-secondary" disabled>
          {% endif %}
              <i class="fa fa-download"></i>
              Generate &amp; Download
            </button>
        </form>
        <br/>
        <p><b>Important:</b> Keep your private key in a safe place. Anyone with access to the private key will be able to access your data on {{site_title|default:'MyTardis'}}.</p>
        <div id="keyGenerateAlert" class="alert alert-danger" style="display: none">
          <div id="keyGenerateAlertMessage"></div>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-outline-secondary" data-dismiss="modal" onclick="sftp.clearKeyGenerateForm()">
          <i class="fa fa-close"></i>
          Close
        </button>
      </div>
    </div>  <!-- class="modal-content" -->
  </div>  <!-- class="modal-dialog" -->
</div>
{% endblock content %}